//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symlinker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Symlinker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2010-{1} Alejandro Mora
        ///Version: {0}
        ///e-mail: mail@alejandro.md
        ///
        ///Thanks to Microsoft for the use of their shortcut arrow :).
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ButtonAbout {
            get {
                return ResourceManager.GetString("ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another.
        /// </summary>
        public static string ButtonAddAnother {
            get {
                return ResourceManager.GetString("ButtonAddAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create link.
        /// </summary>
        public static string ButtonCreateLink {
            get {
                return ResourceManager.GetString("ButtonCreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINK LOCATION.
        /// </summary>
        public static string CardHeaderLinkLocation {
            get {
                return ResourceManager.GetString("CardHeaderLinkLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARGET.
        /// </summary>
        public static string CardHeaderTarget {
            get {
                return ResourceManager.GetString("CardHeaderTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the command-line tool needed to create links..
        /// </summary>
        public static string CmdNotFound {
            get {
                return ResourceManager.GetString("CmdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with this link name already exists in the selected directory. Would you like to delete it and create a new link?.
        /// </summary>
        public static string DialogDeleteFile {
            get {
                return ResourceManager.GetString("DialogDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        public static string DialogDeleteFileWarning {
            get {
                return ResourceManager.GetString("DialogDeleteFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder with this link name already exists in the selected directory. Would you like to delete it and create a new link?.
        /// </summary>
        public static string DialogFolderExists {
            get {
                return ResourceManager.GetString("DialogFolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder already exists.
        /// </summary>
        public static string DialogFolderExistsDialog {
            get {
                return ResourceManager.GetString("DialogFolderExistsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the specified directories or files does not exist. Please provide valid paths..
        /// </summary>
        public static string FilesOrFolderNotExists {
            get {
                return ResourceManager.GetString("FilesOrFolderNotExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paths cannot contain quote characters. Please remove any quotes and try again..
        /// </summary>
        public static string InvalidQuoteInPath {
            get {
                return ResourceManager.GetString("InvalidQuoteInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all the required fields..
        /// </summary>
        public static string FillBlanks {
            get {
                return ResourceManager.GetString("FillBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link creation was aborted..
        /// </summary>
        public static string LinkCreationAborted {
            get {
                return ResourceManager.GetString("LinkCreationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted.
        /// </summary>
        public static string LinkCreationAbortedWarning {
            get {
                return ResourceManager.GetString("LinkCreationAbortedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link successfully created..
        /// </summary>
        public static string LinkSuccessfullyCreated {
            get {
                return ResourceManager.GetString("LinkSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MessageBoxAboutTitle {
            get {
                return ResourceManager.GetString("MessageBoxAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred:.
        /// </summary>
        public static string MessageBoxExceptionOcurred {
            get {
                return ResourceManager.GetString("MessageBoxExceptionOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBoxSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string PillFile {
            get {
                return ResourceManager.GetString("PillFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string PillFolder {
            get {
                return ResourceManager.GetString("PillFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard link.
        /// </summary>
        public static string PillHardLink {
            get {
                return ResourceManager.GetString("PillHardLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junction.
        /// </summary>
        public static string PillJunction {
            get {
                return ResourceManager.GetString("PillJunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic link.
        /// </summary>
        public static string PillSymbolicLink {
            get {
                return ResourceManager.GetString("PillSymbolicLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link name.
        /// </summary>
        public static string PlaceholderLinkName {
            get {
                return ResourceManager.GetString("PlaceholderLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\path\to\location.
        /// </summary>
        public static string PlaceholderLinkPath {
            get {
                return ResourceManager.GetString("PlaceholderLinkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target file.
        /// </summary>
        public static string PlaceholderTargetFile {
            get {
                return ResourceManager.GetString("PlaceholderTargetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder.
        /// </summary>
        public static string PlaceholderTargetFolder {
            get {
                return ResourceManager.GetString("PlaceholderTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\path\to\target.
        /// </summary>
        public static string PlaceholderTargetPath {
            get {
                return ResourceManager.GetString("PlaceholderTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Symlinker.
        /// </summary>
        public static string TooltipAbout {
            get {
                return ResourceManager.GetString("TooltipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose where the link will be created and give it a name.
        ///Click the icon or drag and drop a folder here..
        /// </summary>
        public static string TooltipLinkLocationCard {
            get {
                return ResourceManager.GetString("TooltipLinkLocationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the link type: symbolic link or hard link.
        ///Use symbolic links as the default..
        /// </summary>
        public static string TooltipLinkTypeFileDescription {
            get {
                return ResourceManager.GetString("TooltipLinkTypeFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the link type: symbolic link, hard link, or directory junction.
        ///Use symbolic links as the default..
        /// </summary>
        public static string TooltipLinkTypeFolderDescription {
            get {
                return ResourceManager.GetString("TooltipLinkTypeFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic link types.
        /// </summary>
        public static string TooltipLinkTypeTitle {
            get {
                return ResourceManager.GetString("TooltipLinkTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the real file or folder the link will point to.
        ///Click the icon or drag and drop a file/folder here..
        /// </summary>
        public static string TooltipTargetCard {
            get {
                return ResourceManager.GetString("TooltipTargetCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose between file mode (link a file to another file)
        ///or folder mode (link a folder to another folder)..
        /// </summary>
        public static string TooltipTypeSelectorDescription {
            get {
                return ResourceManager.GetString("TooltipTypeSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic link type selector.
        /// </summary>
        public static string TooltipTypeSelectorTitle {
            get {
                return ResourceManager.GetString("TooltipTypeSelectorTitle", resourceCulture);
            }
        }
    }
}
