name: Release

on:
  push:
    tags: [v*]

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Git
        run: |
          git config --global url."https://user:${{ secrets.GITHUB_TOKEN }}@github".insteadOf https://github
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Extract version from tag
        id: version
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          $version = $tag.TrimStart('v')
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Version: $version"

      - name: Build portable distribution for Scoop
        shell: pwsh
        run: ./build-portable.ps1 -Version ${{ steps.version.outputs.version }}

      - name: Create GitHub Release with portable ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: symlinker-${{ steps.version.outputs.version }}-portable.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ClickOnce release script
        shell: pwsh
        run: ./release.ps1